"use client";
import "./globals.css";
import "react-modern-drawer/dist/index.css";
import { AppProgressBar as ProgressBar } from "next-nprogress-bar";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import Header from "../components/header/header";
import Footer from "../components/footer/footer";
import CategoriesSlider from "../components/categories/categories";
import TopItemAndPrice from "../components/common/topItemAndPrice/topItemAndPrice";

import store from "../redux/store";
import { Provider } from "react-redux";
import { ThemeProvider } from "next-themes";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Provider store={store}>
          <ThemeProvider attribute="class">
            <Header />
            <CategoriesSlider />
            {children}
            <ProgressBar
              height="4px"
              color="#fff"
              options={{ showSpinner: false }}
              shallowRouting
            />
            <TopItemAndPrice />
            <Footer />
          </ThemeProvider>
        </Provider>
      </body>
    </html>
  );
}
